# Generated by Django 4.1.7 on 2024-05-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='body',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='threads',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='threads',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='threads',
            name='topic',
        ),
    ]
