# Generated by Django 4.1.7 on 2024-05-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='created_by',
        ),
    ]
